<table class="table table-responsive table-striped">
    <thead>
        <tr>
            <th><?= $this->translate('resource') ?></th>
            <th><?= $this->translate('username') ?></th>
            <th><?= $this->translate('status') ?></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($accesses as $access) : ?>
            <tr>
                <td><?= $this->escapeHtml($access->getResourceName()) ?></td>
                <td><?= $this->escapeHtml($access->getUsername()) ?></td>
                <td><?= $this->escapeHtml($access->getStatusAsString()) ?></td>
                <td>
                    <?php if (1 == 1): ?>
                        <a class="btn btn-sm btn-danger" href="<?= $this->url('access', ['action' => 'disable', 'id' => $access->getAccessId()]) ?>"><i class="fas fa-ban"></i> <?= $this->translate('disable') ?></a>
                    <?php endif; ?>
                <td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
