<ul class="nav navbar-nav">
    <?php foreach ($container as $page): ?>
        <?php
        //var_dump(get_class_methods($page));
        //$parent = $page->getParent();
        //var_dump(get_class_methods($parent));
        //var_dump($page->getParent());
        //exit();
        $active_class = 'active';
        ?>
        <li class="<?= $active_class ?>">
            <a href="<?= $page->getHref() ?>"><?= $page->getLabel() ?></a>
        </li>
    <?php endforeach ?>
</ul>

<?php

?>
