<ul class="navbar-nav mr-auto">
    <?php foreach ($container as $page): ?>
        <?php
        if ($page->getRouteMatch()) :
            $matched_route_name = $page->getRouteMatch()->getMatchedRouteName();

            $parent_route = explode("/", $matched_route_name);

            $active_class = ($parent_route[0] == $page->getRoute()) ? 'active' : '';
            ?>
            <li class="nav-item <?= $active_class ?>">
                <a class="nav-link" href="<?= $page->getHref() ?>"><?= $page->getLabel() ?></a>
            </li>
        <?php endif; ?>
    <?php endforeach ?>
</ul>
