<?php
// module/Application/view/partial/paginator.phtml
?>
<ul class="pagination">
    <?php if (isset($this->previous)): ?>
        <li class="page-item"><a class="page-link" href="<?= $this->url($this->route, ['action' => $this->action, 'id' => $this->previous], ['query' => $this->query]) ?>"><?= $this->translate('Previous') ?></a></li>
    <?php else: ?>
        <li class="page-item disabled"><span class="page-link"><?= $this->translate('Previous') ?></span></li>
    <?php endif ?>


    <?php foreach ($this->pagesInRange as $page): ?>
        <?php if ($page !== $this->current): ?>
            <li class="page-item">
                <a class="page-link" href="<?= $this->url($this->route, ['action' => $this->action, 'id' => $page], ['query' => $this->query]) ?>"><?= $page ?></a>
            </li>
        <?php else: ?>
            <li class="page-item active">
                <span class="page-link">
                    <?= $page ?>
                    <span class="sr-only">(current)</span>
                </span>
            </li>
        <?php endif ?>
    <?php endforeach ?>

    <?php if (isset($this->next)): ?>
        <li class="page-item"><a class="page-link" href="<?= $this->url($this->route, ['action' => $this->action, 'id' => $this->next], ['query' => $this->query]) ?>"><?= $this->translate('Next') ?></a></li>
    <?php else: ?>
        <li class="page-item disabled"><span class="page-link"><?= $this->translate('Next') ?></span></li>
    <?php endif ?>
</ul>
