<?php
//module/User/view/user/user/change-password.phtml
$title = $this->translate('Alterar Senha');
$this->headTitle($title);
$form->setAttributes(['class' => 'form-horizontal']);
$form->prepare();
?>

<div class="wrapper wrapper-content animated fadeInRight">
	<div class="row">
		<div class="col-lg-12">
			<div class="ibox float-e-margins">
				<div class="ibox-title">
					<h5><h1>Change Password for <?php //$this->escapeHtml($user->getEmail()) ?></h1></h5>
				</div>
				<div class="ibox-content">
					<?= $this->form()->openTag($form) ?>
					<?= $this->formElement($form->get('csrf')) ?>

					<?php $element = $form->get('old_password') ?>
					<div class="form-group">
						<?= $this->formLabel($element->setOptions(['label_attributes' => ['class' => 'col-sm-3 control-label']])) ?>
						<div class="col-sm-6">
							<?= $this->formInput($element->setAttributes(['class' => 'form-control', 'placeholder' => 'Enter old password'])) ?>
							<?= $this->formElementErrors($element) ?>
						</div>
					</div>
					<div class="hr-line-dashed"></div>

					<?php $element = $form->get('new_password') ?>
					<div class="form-group">
						<?= $this->formLabel($element->setOptions(['label_attributes' => ['class' => 'col-sm-3 control-label']])) ?>
						<div class="col-sm-6">
							<?= $this->formElement($element->setAttributes(['class' => 'form-control', 'placeholder' => 'Enter new password'])) ?>
							<?= $this->formElementErrors($element) ?>
						</div>
					</div>
					<div class="hr-line-dashed"></div>

					<?php $element = $form->get('confirm_new_password') ?>
					<div class="form-group">
						<?= $this->formLabel($element->setOptions(['label_attributes' => ['class' => 'col-sm-3 control-label']])) ?>
						<div class="col-sm-6">
							<?= $this->formElement($element->setAttributes(['class' => 'form-control', 'placeholder' => 'Re-enter new password'])) ?>
							<?= $this->formElementErrors($element) ?>
						</div>
					</div>
					<div class="hr-line-dashed"></div>

					<?php $element = $form->get('submit') ?>
					<div class="form-group">
						<div class="col-sm-4 col-sm-offset-3">
							<?= $this->formElement($element->setAttributes(['class' => 'btn btn-primary'])) ?>
							<a class="btn btn-white" href="<?= $this->url('users') ?>"><?= $this->translate('Cancelar') ?></a>
						</div>
					</div>

					<?= $this->form()->closeTag() ?>
				</div>
			</div>
		</div>
	</div>
</div>
