<?php
//module/User/view/user/user/edit.phtml
$title = $this->translate('Editar Usuário - ' . $user->getFullName());
$this->headTitle($title);
$form->setAttributes(['class' => 'form-horizontal']);
$form->prepare();
?>

<div class="wrapper wrapper-content animated fadeInRight">
	<div class="row">
		<div class="col-lg-12">
			<div class="ibox float-e-margins">
				<div class="ibox-title">
					<h5>Preencha o formulário para atualizar o cadastro</h5>
				</div>
				<div class="ibox-content">
					<?= $this->form()->openTag($form) ?>

					<?php $element = $form->get('email') ?>
					<div class="form-group">
						<?= $this->formLabel($element->setOptions(['label_attributes' => ['class' => 'col-sm-3 control-label']])) ?>
						<div class="col-sm-6">
							<?= $this->formInput($element->setAttributes(['class' => 'form-control'])) ?>
							<?= $this->formElementErrors($element) ?>
						</div>
					</div>
					<div class="hr-line-dashed"></div>

					<?php $element = $form->get('full_name') ?>
					<div class="form-group">
						<?= $this->formLabel($element->setOptions(['label_attributes' => ['class' => 'col-sm-3 control-label']])) ?>
						<div class="col-sm-6">
							<?= $this->formElement($element->setAttributes(['class' => 'form-control'])) ?>
							<?= $this->formElementErrors($element) ?>
						</div>
					</div>
					<div class="hr-line-dashed"></div>

					<?php $element = $form->get('status') ?>
					<div class="form-group">
						<?= $this->formLabel($element->setOptions(['label_attributes' => ['class' => 'col-sm-3 control-label']])) ?>
						<div class="col-sm-6">
							<?= $this->formElement($element->setAttributes(['class' => 'form-control'])) ?>
							<?= $this->formElementErrors($element) ?>
						</div>
					</div>
					<div class="hr-line-dashed"></div>

					<?php $element = $form->get('submit') ?>
					<div class="form-group">
						<div class="col-sm-4 col-sm-offset-3">
							<?= $this->formElement($element->setAttributes(['class' => 'btn btn-primary'])) ?>
							<a class="btn btn-white" href="<?= $this->url('users') ?>">Cancelar</a>
						</div>
					</div>

					<?= $this->form()->closeTag() ?>
				</div>
			</div>
		</div>
	</div>
</div>
