<?php
//module/User/view/user/user/index.phtml
$title = 'Administração de Usuários';
$this->headTitle($title);
?>

<div class="wrapper wrapper-content animated fadeInRight">
	<div class="row">
		<div class="col-lg-12">
			<div class="ibox float-e-margins">
				<div class="ibox-title">
					<a class="btn btn-primary btn-sm" href="<?= $this->url('users', ['action'=>'add']) ?>"><i class="fa fa-plus" aria-hidden="true"></i> Adicionar Usuário</a>
				</div>
				<div class="ibox-content">
					<table class="table table-striped table-responsive">
						<thead>
							<tr>
								<th>E-mail</th>
								<th>Nome</th>
								<th>Data de Criação</th>
								<th>Status</th>
								<th>Ações</th>
							</tr>
						</thead>
						<tbody>
							<?php foreach ($users as $user): ?>
								<tr>
									<td>
										<a href="<?= $this->url('users', ['action' => 'view', 'id' => $user->getId()]) ?>"><?= $this->escapeHtml($user->getEmail()) ?></a>
									</td>
									<td><?= $this->escapeHtml($user->getFullName()) ?></td>
									<td><?= $this->escapeHtml($user->getDateCreated()) ?></td>
									<td><?= $this->escapeHtml($user->getStatusAsString()) ?></td>
									<td>
										<a class="btn btn-sm btn-primary" href="<?= $this->url('users', ['action' => 'edit', 'id' => $user->getId()]) ?>"><i class="fa fa-pencil" aria-hidden="true"></i>&nbsp;Editar</a>
										<a class="btn btn-sm btn-default" href="<?= $this->url('users', ['action' => 'reset-password', 'id' => $user->getId()]) ?>"><i class="fa fa-asterisk" aria-hidden="true"></i>&nbsp;Resetar Senha</a>
									</td>
								</tr>
							<?php endforeach; ?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
