<?php
$this->headTitle('View User');
?>

<h1>View User</h1>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
             <tr>
                <th>ID:</th>
                <td><?= $this->escapeHtml($user->getId()) ?></th>
            </tr>
            <tr>
                <th>E-mail:</th>
                <td><?= $this->escapeHtml($user->getEmail()) ?></th>
            </tr>
            <tr>
                <th>Full Name:</th>
                <td><?= $this->escapeHtml($user->getFullName()) ?></th>
            </tr>
            <tr>
                <th>Date Created:</th>
                <td><?= $this->escapeHtml($user->getDateCreated()) ?></th>
            </tr>
            <tr>
                <th>Status:</th>
                <td><?= $this->escapeHtml($user->getStatusAsString()) ?></th>
            </tr>
        </table>
    </div>
</div>
