web:
  container_name: idm-web
  build: .
  dockerfile: Dockerfile
  ports:
   - "8080:80"
  links:
    - db
  volumes:
   - .:/var/www
db:
  container_name: idm-mysql
  image: mysql:5.7
  ports:
   - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: 123456
    MYSQL_DATABASE: idm
    MYSQL_USER: idm_dbuser
    MYSQL_PASSWORD: idm_dbpasswd
