<?php
// module/Access/view/access/access/detail.phtml
$title = $this->translate('detail_access');
$this->headTitle($title);
?>

<div class="row">
    <div class="col-lg-4">
        <h4><?= $this->escapeHtml('info') ?></h4>
        <a class="btn btn-primary" href="<?= $this->url('access', ['action' => 'edit', 'id' => $access->getAccessId()]) ?>"><i class="fas fa-edit"></i> <?= $this->translate('edit_access') ?></a>
        <a class="btn btn-danger" href="<?= $this->url('access', ['action' => 'edit', 'id' => $access->getAccessId()]) ?>"><i class="fas fa-ban"></i> <?= $this->translate('disable_access') ?></a>
    </div>
    <div class="col-lg-4">
        <h4><?= $this->escapeHtml('resource') ?></h4>
        <p><b><?= $this->translate('name') ?>:</b> <?= $this->escapeHtml($resource->getName()) ?></p>
        <a class="btn btn-primary" href="<?= $this->url('resource', ['action' => 'detail', 'id' => $resource->getResourceId()]) ?>"><i class="fas fa-search-plus"></i> <?= $this->translate('detail_resource') ?></a>
    </div>
    <div class="col-lg-4">
        <h4><?= $this->escapeHtml('user') ?></h4>
        <?php if (!$access->isOrphan()): ?>
            <p><b><?= $this->translate('name') ?>:</b> <?= $this->escapeHtml($user->getFullName()) ?></p>
            <p><b><?= $this->translate('email') ?>:</b> <?= $this->escapeHtml($user->getEmail()) ?></p>
            <p><b><?= $this->translate('position') ?>:</b> <?= $this->escapeHtml($user->getPosition()) ?></p>
            <p><b><?= $this->translate('supervisor') ?>:</b> <?= $this->escapeHtml($user->getSupervisorName()) ?></p>
            <a class="btn btn-primary" href="<?= $this->url('user', ['action' => 'detail', 'id' => $user->getUserId()]) ?>"><i class="fas fa-search-plus"></i> <?= $this->translate('detail_user') ?></a>
        <?php endif; ?>
    </div>
</div>
