<?php
// module/Access/view/access/access/edit.phtml
$title = $this->translate('Edit Access');
$this->headTitle($title);
?>

<div class="row">
    <div class="col-lg-6">

        <?php $form->prepare() ?>

        <?= $this->form()->openTag($form) ?>

        <div class="form-group">
            <label for="comment">Comment</label>
            <input type="text" class="form-control" name="comment" value="<?= $access->getComment() ?>" disabled="disabled">
        </div>

        <div class="form-group">
            <?= $this->formRow($form->get('username')->setAttributes(['class' => 'form-control', 'readonly' => 'readonly'])) ?>
        </div>

        <div class="form-group">
            <?= $this->formRow($form->get('resource_resource_id')->setAttributes(['class' => 'form-control', 'readonly' => 'readonly'])) ?>
        </div>

        <div class="form-group">
            <?= $this->formRow($form->get('user_user_id')->setAttributes(['class' => 'form-control chosen-select'])) ?>
        </div>

        <?= $this->formSubmit($form->get('submit')->setAttributes(['class' => 'btn btn-primary'])) ?>

        <?= $this->form()->closeTag() ?>

    </div>
    <div class="col-lg-6">
        <a class="btn btn-sm btn-primary" href="<?= $this->url('access', ['action' => 'set-generic', 'id' => $access->getAccessId()]) ?>"><i class="fab fa-slideshare"></i> <?= $this->translate('Set As Generic') ?></a>
    </div>
</div>
