<?php
// module/Access/view/access/access/edit.phtml
$title = $this->translate('Edit Access');
$this->headTitle($title);
?>


<div class="row">
    <div class="col-lg-12">

        <?php $form->prepare() ?>

        <?= $this->form()->openTag($form) ?>

        <div class="form-group">
            <?= $this->formRow($form->get('username')->setAttributes(['class' => 'form-control'])) ?>
        </div>

        <div class="form-group">
            <?= $this->formRow($form->get('resources_resource_id')->setAttributes(['class' => 'form-control'])) ?>
        </div>

        <div class="form-group">
            <?= $this->formRow($form->get('users_user_id')->setAttributes(['class' => 'form-control'])) ?>
        </div>

        <div class="form-group">
            <?= $this->formRow($form->get('status')->setAttributes(['class' => 'form-control datepicker'])) ?>
        </div>

        <?= $this->formSubmit($form->get('submit')->setAttributes(['class' => 'btn btn-primary'])) ?>

        <?= $this->form()->closeTag() ?>

    </div>
</div>
