<?php
// module/Access/view/access/access/index.phtml
$title = $this->translate('Accesses');
$this->headTitle($title);
?>

<div class="row">
    <div class="col-lg-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?= $this->translate('Search') ?></h3>
            </div>
            <div class="panel-body">
                <?php $form->setAttribute('method', 'get') ?>
                <?php $form->prepare() ?>
                <?= $this->form()->openTag($form) ?>

                <div class="form-group">
                    <?= $this->formRow($form->get('username')->setAttributes(['class' => 'form-control'])) ?>
                </div>

                <div class="form-group">
                    <?= $this->formRow($form->get('status')->setAttributes(['class' => 'form-control'])) ?>
                </div>

                <div class="form-group">
                    <?= $this->formSubmit($form->get('submit')->setAttributes(['class' => 'btn btn-primary'])) ?>
                </div>

                <?= $this->form()->closeTag() ?>
            </div>
        </div>
    </div>
    <div class="col-lg-9">
        <table class="table table-responsive table-striped table-condensed">
            <thead>
                <tr>
                    <th></th>
                    <th><?= $this->translate('Resource') ?></th>
                    <th><?= $this->translate('Username') ?></th>
                    <th><?= $this->translate('Full Name') ?></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($accesses as $access) : ?>
                    <tr>
                        <td><?= $this->escapeHtml($access->getStatus()) ?></td>
                        <td><?= $this->escapeHtml($access->getResourceName()) ?></td>
                        <td><?= $this->escapeHtml($access->getUsername()) ?></td>
                        <td><?= $this->escapeHtml($access->getUserFullName()) ?></td>
                        <td>
                            <div class="dropdown">
                                <button class="btn btn-sm btn-primary dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                    <?= $this->translate('Options') ?>
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                                    <li><a href="<?= $this->url('access', ['action' => 'details', 'id' => $access->getAccessId()]) ?>"><i class="fas fa-search-plus"></i> <?= $this->translate('Details') ?></a></li>
                                    <li><a href="<?= $this->url('access', ['action' => 'edit', 'id' => $access->getAccessId()]) ?>"><i class="fas fa-edit"></i> <?= $this->translate('Edit') ?></a></li>
                                    <li role="separator" class="divider"></li>
                                    <li><a href="<?= $this->url('access', ['action' => 'disable', 'id' => $access->getAccessId()]) ?>"><i class="fas fa-ban"></i> <?= $this->translate('Disable') ?></a></li>
                                </ul>
                            </div>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
