<?php
// module/Access/view/access/access/index.phtml
$title = $this->translate('accesses');
$this->headTitle($title);
?>

<div class="row">
    <div class="col-lg-12">
        <table class="table table-responsive table-striped">
            <thead>
                <tr>
                    <th><?= $this->translate('status') ?></th>
                    <th><?= $this->translate('resource') ?></th>
                    <th><?= $this->translate('username') ?></th>
                    <th><?= $this->translate('full_name') ?></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($accesses as $access) : ?>
                    <tr>
                        <td><?= $this->escapeHtml($access->getStatus()) ?></td>
                        <td><?= $this->escapeHtml($access->getResourceName()) ?></td>
                        <td><?= $this->escapeHtml($access->getUsername()) ?></td>
                        <td><?= $this->escapeHtml($access->getUserFullName()) ?></td>
                        <td>
                            <a class="btn btn-sm btn-primary" href="<?= $this->url('access', ['action' => 'detail', 'id' => $access->getAccessId()]) ?>"><i class="fas fa-search-plus"></i> <?= $this->translate('detail') ?></a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
