<?php
// module/Access/view/access/access/edit.phtml
$title = $this->translate('Link Access');
$this->headTitle($title);
?>


<div class="row">
    <div class="col-lg-6">

        <?php $form->prepare() ?>

        <?= $this->form()->openTag($form) ?>

        <div class="form-group">
            <input type="text" class="form-control" value="<?= $access->comment ?>" disabled=disabled>
        </div>

        <div class="form-group">
            <?= $this->formRow($form->get('username')->setAttributes(['class' => 'form-control', 'disabled' => 'disabled'])) ?>
        </div>

        <div class="form-group">
            <?= $this->formRow($form->get('resources_resource_id')->setAttributes(['class' => 'form-control', 'disabled' => 'disabled'])) ?>
        </div>

        <div class="form-group">
            <?= $this->formRow($form->get('users_user_id')->setAttributes(['class' => 'form-control chosen-select'])->setOptions(['empty_option' => 'Select an user...'])) ?>
        </div>

        <?= $this->formSubmit($form->get('submit')->setAttributes(['class' => 'btn btn-primary'])) ?>

        <?= $this->form()->closeTag() ?>

    </div>
</div>
