<?php
// module/Access/view/access/access/orphans.phtml
$title = $this->translate('Orphans');
$this->headTitle($title);
?>

<div class="row">
    <div class="col-lg-12">
        <table class="table table-responsive table-striped table-condensed">
            <thead>
                <tr>
                    <th><?= $this->translate('Status') ?></th>
                    <th><?= $this->translate('Resource') ?></th>
                    <th><?= $this->translate('Username') ?></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($accesses as $access) : ?>
                    <tr>
                        <td>
                            <?php $label = ($access->isEnabled()) ? 'success' : 'default' ?>
                        </td>
                        <td><?= $this->escapeHtml($access->getResourceName()) ?></td>
                        <td><?= $this->escapeHtml($access->getUsername()) ?></td>

                        <td>
                            <?php if (1 == 1): ?>
                                <a class="btn btn-sm btn-primary" href="<?= $this->url('access', ['action' => 'edit', 'id' => $access->getAccessId()]) ?>"><i class="fas fa-edit"></i> <?= $this->translate('Edit') ?></a>
                            <?php endif; ?>
                        <td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>

    </div>
</div>
