<?php
// module/Organization/view/organization/internal/add.phtml
$title = $this->translate('Add Internal');
$this->headTitle($title);
?>

<div class="row">
    <div class="col-lg-6">

        <?php $form->prepare() ?>

        <?= $this->form()->openTag($form) ?>

        <div class="form-group">
            <?= $this->formRow($form->get('alias')->setAttributes(['class' => 'form-control'])) ?>
        </div>

        <div class="form-group">
            <?= $this->formRow($form->get('name')->setAttributes(['class' => 'form-control'])) ?>
        </div>

        <div class="form-group">
            <?= $this->formRow($form->get('employer_number')->setAttributes(['class' => 'form-control'])) ?>
        </div>

        <?= $this->formSubmit($form->get('submit')->setAttributes(['class' => 'btn btn-primary'])) ?>

        <?= $this->form()->closeTag() ?>

    </div>
</div>
