<?php
// module/Organization/view/organization/internal/index.phtml
$title = $this->translate('Internals');
$this->headTitle($title);
?>

<div class="row">
    <div class="col-lg-12">
        <a class="btn btn-primary pull-right" href="<?= $this->url('organization/internal', ['action' => 'add']) ?>"><i class="fa fa-plus"></i> <?= $this->translate('Add Internal') ?></a>
        <?= $this->partial('organization/table', ['organizations' => $organizations]) ?>
    </div>
</div>
