<?php
// module/Organization/view/organization/organization/details.phtml
$title = $this->translate('Organization Details');
$this->headTitle($title);
?>

<div class="row">
    <div class="col-lg-6">
        <table class="table table-responsive table-condensed table-striped table-bordered">
            <thead>
                <tr>
                    <th colspan="2"><?= $this->escapeHtml($organization->getAlias()) ?></th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th><?= $this->translate('Name') ?></th>
                    <td><?= $this->escapeHtml($organization->getName()) ?></td>
                </tr>
                <tr>
                    <th><?= $this->translate('Employer Number') ?></th>
                    <td><?= $this->escapeHtml($organization->getEmployerNumber()) ?></td>
                </tr>
                <?php if ($organization->isExternal()) : ?>
                    <tr>
                        <th><?= $this->translate('Expires On') ?></th>
                        <td><?= $this->escapeHtml($organization->getExpiresOn()) ?></td>
                    </tr>
                <?php endif; ?>
                <tr>
                    <th><?= $this->translate('Enabled') ?></th>
                    <td>
                        <?php if ($organization->isEnabled()) : ?>
                            <span class="label label-success"><?= $this->translate('Enabled') ?></span>
                        <?php endif; ?>
                    </td>
                </tr>
                <?php if ($organization->isExternal()) : ?>
                    <tr>
                        <th><?= $this->translate('Owners') ?></th>
                        <td>
                            <?php foreach($owners as $owner) : ?>
                                <a href="<?= $this->url('user/user', ['action' => 'details', 'id' => $owner->getUserId()]) ?>"><?= $this->escapeHtml($owner->getFullName()) ?></a><br>
                            <?php endforeach; ?>
                        </td>
                    </tr>
                <?php endif; ?>
                <tr>
                    <th><?= $this->translate('Created On') ?></th>
                    <td><?= $this->escapeHtml($organization->getCreatedOn()) ?></td>
                </tr>
                <tr>
                    <th><?= $this->translate('Update On') ?></th>
                    <td><?= $this->escapeHtml($organization->getUpdatedOn()) ?></td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class="col-lg-6">
        <a class="btn btn-primary" href="<?= $this->url('organization/organization', ['action' => 'edit', 'id' => $organization->getOrganizationId()]) ?>"><i class="fas fa-edit"></i> <?= $this->translate('Edit Organization') ?></a>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class="active"><a href="#users" aria-controls="users" role="tab" data-toggle="tab"><?= $this->translate('Users') ?></a></li>
        </ul>

        <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="users">
                <?= $this->partial('user/table', ['users' => $users]) ?>
            </div>
        </div>
    </div>
</div>
