<?php
// module/Organization/view/organization/organization/search.phtml
$title = 'organizations';
$this->headTitle($title);
?>

<div class="row bg-light">
    <div class="col-lg-12">
        <?php $form->prepare() ?>
        <?= $this->form()->openTag($form) ?>

        <div class="row">
            <div class="col-md-3">
                <div class="form-group">
                    <?= $this->formRow($form->get('alias')->setAttributes(['class' => 'form-control'])) ?>
                </div>
            </div>

            <div class="col-md-3">
                <div class="form-group">
                    <?= $this->formRow($form->get('name')->setAttributes(['class' => 'form-control'])) ?>
                </div>
            </div>

            <div class="col-md-2">
                <div class="form-group">
                    <?= $this->formRow($form->get('type')->setAttributes(['class' => 'form-control'])) ?>
                </div>
            </div>

            <div class="col-md-2">
                <div class="form-group">
                    <?= $this->formRow($form->get('status')->setAttributes(['class' => 'form-control'])) ?>
                </div>
            </div>

            <div class="col-md-2">
                <div class="form-group">
                    <?= $this->formSubmit($form->get('submit')->setAttributes(['class' => 'btn btn-primary'])) ?>
                </div>
            </div>
        </div>

        <?= $this->form()->closeTag() ?>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <table class="table table-responsive table-striped">
            <thead>
                <tr>
                    <th><?= $this->translate('status') ?></th>
                    <th><?= $this->translate('alias') ?></th>
                    <th><?= $this->translate('name') ?></th>
                    <th><?= $this->translate('employer_number') ?></th>
                    <th><?= $this->translate('created_on') ?></th>
                    <th><?= $this->translate('expires_on') ?></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($organizations as $organization) : ?>
                    <tr>
                        <td></td>
                        <td><?= $this->escapeHtml($organization->getAlias()) ?></td>
                        <td><?= $this->escapeHtml($organization->getName()) ?></td>
                        <td><?= $this->escapeHtml($organization->getEmployerNumber()) ?></td>
                        <td><?= $this->escapeHtml($organization->getCreatedOn()) ?></td>
                        <td><?= $this->escapeHtml($organization->getExpiresOn()) ?></td>
                        <td>
                            <a class="btn btn-sm btn-primary" href="<?= $this->url('organization/organization', ['action' => 'detail', 'id' => $organization->getOrganizationId()]) ?>"><i class="fas fa-search-plus"></i> <?= $this->translate('detail') ?></a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
