<table class="table table-responsive table-striped dataTable">
    <thead>
        <tr>
            <th><?= $this->translate('Enabled') ?></th>
            <th><?= $this->translate('Name') ?></th>

            <th><?= $this->translate('External') ?></th>
            <th><?= $this->translate('Options') ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($users as $user) : ?>
            <tr>
                <td>
                    <?php if ($user->isEnabled()) : ?>
                        <span class="label label-success"><?= $this->translate('Enabled') ?></span>
                    <?php endif; ?>
                </td>
                <td><?= $this->escapeHtml($user->getFullName()) ?></td>
                <td>
                    <?php if ($user->isOrganizationExternal()) : ?>
                        <span class="label label-default"><?= $this->translate('External') ?></span>
                    <?php endif; ?>
                </td>
                <td>
                    <a class="btn btn-sm btn-primary" href="<?= $this->url('user/user', ['action' => 'details', 'id' => $user->getUserId()]) ?>"><i class="fas fa-search-plus"></i> <?= $this->translate('Detail') ?></a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
