<?php
// module/User/view/user/user/detail.phtml
$title = $this->translate('User Details');
$this->headTitle($title);
?>

<div class="row mb-3">
    <div class="col-lg-6">
        <table class="table table-striped table-bordered">
            <tbody>
                <tr>
                    <th><?= $this->translate('Full Name') ?> :</th>
                    <td><?= $this->escapeHtml($user->getFullName()) ?></td>
                </tr>
                <tr>
                    <th><?= $this->translate('Email') ?> :</th>
                    <td><?= $this->escapeHtml($user->getEmail()) ?></td>
                </tr>
                <tr>
                    <th><?= $this->translate('Position') ?> :</th>
                    <td><?= $this->escapeHtml($user->getPosition()) ?></td>
                </tr>
                <tr>
                    <th><?= $this->translate('Supervisor') ?> :</th>
                    <td><?= $this->escapeHtml($user->getSupervisorName()) ?></td>
                </tr>
                <tr>
                    <th><?= $this->translate('Hiring Date') ?> :</th>
                    <td><?= $this->escapeHtml($user->getHiringDate()) ?></td>
                </tr>
                <tr>
                    <th><?= $this->translate('Resignation Date') ?> :</th>
                    <td><?= $this->escapeHtml($user->getResignationDate()) ?></td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class="col-lg-6">
        <a class="btn btn-primary" href="<?= $this->url('user', ['action' => 'edit', 'id' => $user->getUserId()]) ?>"><i class="fas fa-edit"></i> <?= $this->translate('Edit User') ?></a>
        <a class="btn btn-danger" href="<?= $this->url('user', ['action' => 'disable', 'id' => $user->getUserId()]) ?>"><i class="fas fa-ban"></i> <?= $this->translate('Disable User') ?></a>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <nav>
            <div class="nav nav-tabs" id="nav-tab" role="tablist">
                <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true"><?= $this->translate('Accesses') ?></a>
            </div>
        </nav>
        <div class="tab-content" id="nav-tabContent">
            <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
                <?= $this->partial('access/table', ['accesses' => $accesses]) ?>
            </div>
        </div>
    </div>
</div>
