<?php
// module/User/view/user/user/disable.phtml
$title = $this->translate('Disable User');
$this->headTitle($title);
?>

<div class="row">
    <div class="col-lg-12">

        <p>
            Are you sure that you want to disable "<?= $this->escapeHtml($user->getFullName()) ?>"? All user accesses will be disabled.
        </p>

        <form method="post">
            <div class="form-group">
                <button class="btn btn-danger" type="submit"><?= $this->translate('Yes') ?></button>
                <a class="btn btn-success" href="<?= $this->url('user', ['action' => 'details', 'id' => $user->getUserId()]) ?>"><?= $this->translate('No') ?></a>
            </div>
        </form>

    </div>
</div>
