<?php
// module/User/view/user/user/search.phtml
$title = $this->translate('Users');
$this->headTitle($title);
?>

<div class="row">
    <div class="col-lg-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?= $this->translate('Search') ?></h3>
            </div>
            <div class="panel-body">
                <?php $form->setAttribute('method', 'post') ?>
                <?php $form->prepare() ?>
                <?= $this->form()->openTag($form) ?>

                <div class="form-group">
                    <?= $this->formRow($form->get('full_name')->setAttributes(['class' => 'form-control'])) ?>
                </div>

                <div class="form-group">
                    <?= $this->formSubmit($form->get('submit')->setAttributes(['class' => 'btn btn-primary'])) ?>
                </div>

                <?= $this->form()->closeTag() ?>
            </div>
        </div>
    </div>
    <div class="col-lg-9">
        <?= $this->partial('user/table', ['users' => $users]) ?>
    </div>
</div>
