<?php
// module/User/view/user/user/search.phtml
$title = $this->translate('Users');
$this->headTitle($title);
?>

<div class="row">
    <div class="col-lg-12">
        <?php $form->prepare() ?>
        <?= $this->form()->openTag($form) ?>

        <div class="row">
            <div class="col-md-4">
                <div class="form-group">
                    <?= $this->formRow($form->get('full_name')->setAttributes(['class' => 'form-control'])) ?>
                </div>
            </div>

            <div class="col-md-4">
                <div class="form-group">
                    <?= $this->formSubmit($form->get('submit')->setAttributes(['class' => 'btn btn-primary'])) ?>
                </div>
            </div>
        </div>

        <?= $this->form()->closeTag() ?>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <?= $this->partial('user/table', ['users' => $users]) ?>
    </div>
</div>
