<?php
// module/User/view/user/employee/edit.phtml
$title = $this->translate('Edit Employee');
$this->headTitle($title);
?>

<div class="row">
    <div class="col-lg-12">

        <?php $form->prepare() ?>
        <?= $this->form()->openTag($form) ?>

        <div class="row">
            <div class="col-md-5">
                <div class="form-group">
                    <?= $this->formRow($form->get('full_name')->setAttributes(['class' => 'form-control'])) ?>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-4">
                <div class="form-group">
                    <?= $this->formRow($form->get('birthday_date')->setAttributes(['class' => 'form-control'])) ?>
                </div>
            </div>

            <div class="col-md-4">
                <div class="form-group">
                    <?= $this->formRow($form->get('personal_id')->setAttributes(['class' => 'form-control'])) ?>
                </div>
            </div>

            <div class="col-md-4">
                <div class="form-group">
                    <?= $this->formRow($form->get('work_id')->setAttributes(['class' => 'form-control'])) ?>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-4">
                <div class="form-group">
                    <?= $this->formRow($form->get('hiring_date')->setAttributes(['class' => 'form-control'])) ?>
                </div>
            </div>

            <div class="col-md-4">
                <div class="form-group">
                    <?= $this->formRow($form->get('position')->setAttributes(['class' => 'form-control'])) ?>
                </div>
            </div>

            <div class="col-md-4">
                <div class="form-group">
                    <?= $this->formRow($form->get('supervisor_name')->setAttributes(['class' => 'form-control'])) ?>
                </div>
            </div>
        </div>

        <?= $this->formSubmit($form->get('submit')->setAttributes(['class' => 'btn btn-primary'])) ?>

        <?= $this->form()->closeTag() ?>


    </div>
</div>
