<?php
// module/Resource/view/resource/resource/add.phtml
$title = 'Add Resource';
$this->headTitle($title);
?>

<div class="row">
    <div class="col-lg-12">

        <?php $form->prepare() ?>

        <?= $this->form()->openTag($form) ?>

        <div class="form-group">
            <?= $this->formRow($form->get('name')->setAttributes(['class' => 'form-control'])) ?>
        </div>

        <div class="form-group">
            <?= $this->formRow($form->get('description')->setAttributes(['class' => 'form-control'])) ?>
        </div>

        <div class="form-group">
            <?= $this->formRow($form->get('owners')->setAttributes(['class' => 'form-control chosen-select', 'multiple' => 'multiple'])) ?>
        </div>

        <div class="form-group">
            <?= $this->formRow($form->get('approvers')->setAttributes(['class' => 'form-control chosen-select', 'multiple' => 'multiple'])) ?>
        </div>

        <?= $this->formSubmit($form->get('submit')->setAttributes(['class' => 'btn btn-primary'])) ?>

        <?= $this->form()->closeTag() ?>

    </div>
</div>
