<?php
// module/Resource/view/resource/resource/index.phtml
$title = $this->translate('Resources');
$this->headTitle($title);
?>

<div class="row">
    <div class="col-lg-12">
        <a class="btn btn-success pull-right" href="<?= $this->url('resource', ['action' => 'add']) ?>"><i class="fa fa-plus"></i> <?= $this->translate('Add Resource') ?></a>
        <table class="table table-responsive table-striped">
            <thead>
                <tr>
                    <th><?= $this->translate('name') ?></th>
                    <th><?= $this->translate('status') ?></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($resources as $resource) : ?>
                    <tr>
                        <td><?= $this->escapeHtml($resource->name) ?></td>
                        <td><?= $this->escapeHtml($resource->getStatusAsString()) ?></td>
                        <td>
                            <a class="btn btn-sm btn-primary" href="<?= $this->url('resource', ['action' => 'details', 'id' => $resource->resource_id]) ?>"><i class="fas fa-search-plus"></i> <?= $this->translate('detail') ?></a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
