<?= $this->doctype() ?>
<html lang="en">
<head>
    <?=
    $this->headMeta()
    ->setCharset('UTF-8')
    ->appendName('viewport', 'width=device-width, initial-scale=1, shrink-to-fit=no')
    ?>

    <?=
    $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
    ->prependStylesheet($this->basePath('css/style.css'))
    ->prependStylesheet('//stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css',  'screen', '', ['integrity' => 'sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO', 'crossorigin' => 'anonymous'])
    ->appendStylesheet('//use.fontawesome.com/releases/v5.4.1/css/all.css',  'screen', '', ['integrity' => 'sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz', 'crossorigin' => 'anonymous'])
    ->appendStylesheet($this->basePath('plugins/chosen/chosen.min.css'))
    ->appendStylesheet('//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css')
    ->appendStylesheet('//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/css/bootstrap-datepicker3.min.css')
    ?>

    <?= $this->headTitle('IDM')->setSeparator(' - ')->setAutoEscape(false) ?>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top bg-dark">
            <div class="container">
                <a class="navbar-brand" href="<?= $this->url('home') ?>">
                    <img src="<?= $this->basePath('img/logo.png') ?>" height="18" alt="Netshoes IDM"/>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample07" aria-controls="navbarsExample07" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarsExample07">
                    <?= $this->navigation('navigation')->menu()->setPartial('application/navigation') ?>
                </div>
            </div>
        </nav>

        <main role="main">
            <div class="container">

                <nav aria-label="breadcrumb">
                    <?= $this->navigation('navigation')->breadcrumbs()->setMinDepth(0)->setPartial('application/breadcrumb') ?>
                </nav>

                <div class="row">
                    <div class="col-lg-12 mb-3">
                        <?php $title = $this->headTitle() ?>
                        <h2 class="page-header"><?= $title[0] ?></h2>
                    </div>
                </div>

                <?= $this->content ?>
                <hr>
            </div>
        </main>

        <footer class="container">
            <p>&copy; 2018 - <?= date('Y') ?> by Zend Technologies Ltd. <?= $this->translate('All rights reserved') ?></p>
        </footer>

        <?=
        $this->inlineScript()
        ->prependFile('//stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js', 'text/javascript', ['integrity' => 'sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy', 'crossorigin' => 'anonymous'])
        ->prependFile('//cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js', 'text/javascript', ['integrity' => 'sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49', 'crossorigin' => 'anonymous'])
        ->prependFile('//code.jquery.com/jquery-3.3.1.slim.min.js', 'text/javascript', 'text/javascript', ['integrity' => 'sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo', 'crossorigin' => 'anonymous'])
        ->appendFile($this->basePath('plugins/chosen/chosen.jquery.min.js'))
        ->appendFile('//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js')
        ->appendFile('//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/js/bootstrap-datepicker.min.js')
        ->appendFile($this->basePath('js/idm.js'))
        ?>

    </body>
    </html>
