<?php
// module/Organization/view/organization/organization/details.phtml
$title = $this->translate('Organization Details');
$this->headTitle($title);
?>

<div class="row">
    <div class="col-lg-6">
        <h3><?= $this->escapeHtml($organization->getAlias()) ?></h3>
        <div>
            <p><b><?= $this->translate('name') ?>:</b> <?= $this->escapeHtml($organization->getName()) ?></p>
            <p><b><?= $this->translate('type') ?>:</b> <?= $this->escapeHtml($organization->getTypeAsString()) ?></p>
            <p><b><?= $this->translate('employer_number') ?>:</b> <?= $this->escapeHtml($organization->getEmployerNumber()) ?></p>
            <p><b><?= $this->translate('created_on') ?>:</b> <?= $this->escapeHtml($organization->getCreatedOn()) ?></p>
            <p><b><?= $this->translate('expires_on') ?>:</b> <?= $this->escapeHtml($organization->getExpiresOn()) ?></p>
            <p><b><?= $this->translate('status') ?>:</b> <?= $this->escapeHtml($organization->getStatusAsString()) ?></p>
            <p><b><?= $this->translate('owners') ?>:</b>
                <?php foreach ($owners as $owner): ?>
                    <p><?= $owner->getFullName() ?></p>
                <?php endforeach; ?>
            </p>
        </div>
    </div>
    <div class="col-lg-6">
        <a class="btn btn-primary" href="<?= $this->url('organization/organization', ['action' => 'edit', 'id' => $organization->getOrganizationId()]) ?>"><i class="fas fa-edit"></i> <?= $this->translate('Edit Organization') ?></a>
        <a class="btn btn-danger" href="<?= $this->url('organization/organization', ['action' => 'disable', 'id' => $organization->getOrganizationId()]) ?>"><i class="fas fa-ban"></i> <?= $this->translate('Disable Organization') ?></a>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <?= $this->partial('user/table', ['users' => $users]) ?>
    </div>
</div>
