<?php
// module/Organization/view/organization/organization/search.phtml
$title = $this->translate('Organizations');
$this->headTitle($title);
?>

<div class="row">
    <div class="col-lg-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?= $this->translate('Search') ?></h3>
            </div>
            <div class="panel-body">
                <?php $form->setAttribute('method', 'get') ?>
                <?php $form->prepare() ?>
                <?= $this->form()->openTag($form) ?>

                <div class="form-group">
                    <?= $this->formRow($form->get('alias')->setAttributes(['class' => 'form-control'])) ?>
                </div>

                <div class="form-group">
                    <?= $this->formRow($form->get('name')->setAttributes(['class' => 'form-control'])) ?>
                </div>

                <div class="form-group">
                    <?= $this->formRow($form->get('type')->setAttributes(['class' => 'form-control'])) ?>
                </div>

                <div class="form-group">
                    <?= $this->formRow($form->get('status')->setAttributes(['class' => 'form-control'])) ?>
                </div>

                <div class="form-group">
                    <?= $this->formSubmit($form->get('submit')->setAttributes(['class' => 'btn btn-primary'])) ?>
                </div>

                <?= $this->form()->closeTag() ?>
            </div>
        </div>
    </div>

    <div class="col-lg-9">
        <table class="table table-responsive table-striped table-condensed">
            <thead>
                <tr>
                    <th></th>
                    <th><?= $this->translate('Alias') ?></th>
                    <th><?= $this->translate('Name') ?></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($organizations as $organization) : ?>
                    <tr>
                        <td></td>
                        <td><?= $this->escapeHtml($organization->getAlias()) ?></td>
                        <td><?= $this->escapeHtml($organization->getName()) ?></td>
                        <td>
                            <a class="btn btn-sm btn-primary" href="<?= $this->url('organization/organization', ['action' => 'details', 'id' => $organization->getOrganizationId()]) ?>"><i class="fas fa-search-plus"></i> <?= $this->translate('Details') ?></a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
